import type { GeneratedLesson, LessonLanguage } from "./generation";
import { detectLanguage } from "./generation";

export function generateHTML(lesson: GeneratedLesson): string {
  const lang: LessonLanguage = detectLanguage(
    `${lesson.title ?? ""} ${(lesson.sections ?? []).map((s) => s.heading + " " + s.content).join(" ")}`
  );
  const isRtl = lang === "ar";

  const ui = {
    en: {
      untitled: "Untitled Lesson",
      glossary: "Glossary",
      quiz: "Knowledge Check",
      nav: "Navigation",
      sections: "Sections",
      expand: "Expand",
      collapse: "Collapse",
      submit: "Submit Answers",
      score: "Score",
      correct: "Correct!",
      incorrect: "Incorrect",
      explanation: "Explanation",
      progress: "Progress",
      questions: "questions",
      showAll: "Show All",
      hideAll: "Hide All",
      generatedBy: "Generated by Study Studio",
    },
    ar: {
      untitled: "درس بدون عنوان",
      glossary: "المصطلحات",
      quiz: "اختبر معلوماتك",
      nav: "التنقل",
      sections: "الأقسام",
      expand: "توسيع",
      collapse: "طي",
      submit: "إرسال الإجابات",
      score: "النتيجة",
      correct: "صحيح!",
      incorrect: "خطأ",
      explanation: "التوضيح",
      progress: "التقدم",
      questions: "أسئلة",
      showAll: "عرض الكل",
      hideAll: "إخفاء الكل",
      generatedBy: "تم إنشاؤه بواسطة Study Studio",
    },
  }[lang];

  const dirAttr = isRtl ? ' dir="rtl"' : "";
  const langAttr = `lang="${lang}"`;

  const sectionsJson = JSON.stringify(lesson.sections ?? []);
  const glossaryJson = JSON.stringify(lesson.glossary ?? []);
  const quizJson = JSON.stringify(lesson.quiz ?? []);

  return `<!DOCTYPE html>
<html ${langAttr}${dirAttr}>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${lesson.title || ui.untitled}</title>
<style>
:root {
  --bg: #070b14; --surface: #0c1220; --elevated: #111a2e;
  --card: rgba(255,255,255,0.04); --border: rgba(255,255,255,0.08);
  --border-hover: rgba(255,255,255,0.18);
  --text: #f5f7ff; --text-secondary: #c8d2ff; --text-muted: #8692b1;
  --accent: #7c8bff; --accent-glow: rgba(124,139,255,0.25);
  --green: #4ade80; --red: #f87171; --amber: #fbbf24;
  --gradient: linear-gradient(135deg, #7c8bff 0%, #a78bfa 50%, #ff9f7c 100%);
}
* { margin: 0; padding: 0; box-sizing: border-box; }
html { scroll-behavior: smooth; }
body {
  /* Deliberately NOT 'Inter'. This export is a standalone HTML file with an
     inline stylesheet: it has no access to the app's --font-inter variable and
     no way to reach the self-hosted woff2 files, so naming Inter here would
     reproduce the exact defect fixed in the app shell — a declared font that is
     never loaded, silently falling back anyway. A system stack is what this
     file will actually render with, so it says so.
     To make exports match the app, the font would have to be embedded as
     base64 (roughly +64 KB per exported lesson). See DESIGN.md section 3.1. */
  font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
  background: var(--bg); color: var(--text); line-height: 1.7; overflow-x: hidden;
}
::-webkit-scrollbar { width: 6px; }
::-webkit-scrollbar-track { background: var(--bg); }
::-webkit-scrollbar-thumb { background: var(--accent); border-radius: 3px; }

/* NAV SIDEBAR */
.sidebar {
  position: fixed; top: 0; ${isRtl ? 'right' : 'left'}: 0; width: 280px; height: 100vh;
  background: var(--surface); border-${isRtl ? 'left' : 'right'}: 1px solid var(--border);
  padding: 24px 16px; overflow-y: auto; z-index: 100;
  display: flex; flex-direction: column; gap: 6px;
}
.sidebar-title {
  font-size: 1.1rem; font-weight: 800; letter-spacing: -0.01em;
  background: var(--gradient); -webkit-background-clip: text; background-clip: text;
  -webkit-text-fill-color: transparent; margin-bottom: 12px; padding: 0 8px;
}
.sidebar-label { font-size: 0.7rem; text-transform: uppercase; letter-spacing: 0.12em; color: var(--text-muted); font-weight: 700; padding: 8px 8px 4px; }
.sidebar a {
  display: block; padding: 8px 12px; border-radius: 10px; text-decoration: none;
  color: var(--text-secondary); font-size: 0.85rem; font-weight: 500;
  transition: all .2s; border: 1px solid transparent;
}
.sidebar a:hover { background: var(--card); border-color: var(--border); color: var(--text); }
.sidebar a.active { background: var(--accent-glow); color: var(--accent); border-color: var(--accent); font-weight: 700; }
.sidebar a.q-link { padding-left: 24px; font-size: 0.8rem; }

/* MAIN */
.main { margin-${isRtl ? 'right' : 'left'}: 280px; padding: 40px 48px 80px; max-width: 900px; }

/* PROGRESS */
.progress-bar { position: fixed; top: 0; ${isRtl ? 'right' : 'left'}: 280px; right: 0; height: 3px; z-index: 200; background: var(--surface); }
.progress-fill { height: 100%; background: var(--gradient); width: 0; transition: width .3s ease; }

/* HERO */
.hero { margin-bottom: 48px; }
.hero h1 { font-size: clamp(1.8rem, 4vw, 2.6rem); font-weight: 800; letter-spacing: -0.02em; margin-bottom: 12px; }
.hero .meta { color: var(--text-muted); font-size: 0.85rem; display: flex; gap: 16px; flex-wrap: wrap; }
.hero .badge { display: inline-flex; align-items: center; gap: 6px; padding: 4px 12px; border-radius: 999px; border: 1px solid var(--border); background: var(--card); font-size: 0.78rem; }

/* SECTION CARDS */
.section-card {
  background: var(--card); border: 1px solid var(--border); border-radius: 16px;
  margin-bottom: 16px; overflow: hidden; transition: border-color .2s;
}
.section-card:hover { border-color: var(--border-hover); }
.section-header {
  display: flex; justify-content: space-between; align-items: center;
  padding: 18px 22px; cursor: pointer; user-select: none;
}
.section-header h2 { font-size: 1.1rem; font-weight: 700; }
.section-header .toggle {
  width: 28px; height: 28px; border-radius: 8px; border: 1px solid var(--border);
  background: var(--card); color: var(--text-muted); display: flex; align-items: center;
  justify-content: center; font-size: 0.8rem; transition: all .2s; flex-shrink: 0;
}
.section-card.open .toggle { background: var(--accent-glow); color: var(--accent); border-color: var(--accent); transform: rotate(180deg); }
.section-body { padding: 0 22px 20px; color: var(--text-secondary); font-size: 0.95rem; display: none; }
.section-card.open .section-body { display: block; }

/* GLOSSARY */
.glossary-section { margin-top: 48px; }
.glossary-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 12px; }
.glossary-item {
  background: var(--card); border: 1px solid var(--border); border-radius: 14px;
  padding: 18px 20px; transition: transform .2s, border-color .2s;
}
.glossary-item:hover { transform: translateY(-2px); border-color: var(--accent); }
.glossary-item dt { font-weight: 700; color: var(--accent); font-size: 0.95rem; margin-bottom: 6px; }
.glossary-item dd { color: var(--text-secondary); font-size: 0.88rem; }

/* QUIZ */
.quiz-section { margin-top: 48px; }
.quiz-question {
  background: var(--card); border: 1px solid var(--border); border-radius: 16px;
  padding: 22px; margin-bottom: 14px; transition: border-color .2s;
}
.quiz-question .q-num {
  display: inline-flex; align-items: center; justify-content: center;
  width: 28px; height: 28px; border-radius: 8px; background: var(--accent-glow);
  color: var(--accent); font-weight: 700; font-size: 0.82rem; margin-right: 10px;
}
.quiz-question .q-text { font-weight: 600; font-size: 0.95rem; }
.quiz-options { display: flex; flex-direction: column; gap: 8px; margin-top: 14px; }
.quiz-opt {
  display: flex; align-items: center; gap: 10px; padding: 12px 16px; border-radius: 12px;
  border: 1px solid var(--border); background: var(--surface); cursor: pointer;
  transition: all .2s; font-size: 0.9rem;
}
.quiz-opt:hover { border-color: var(--accent); background: rgba(124,139,255,0.06); }
.quiz-opt.selected { border-color: var(--accent); background: var(--accent-glow); }
.quiz-opt.correct { border-color: var(--green); background: rgba(74,222,128,0.1); }
.quiz-opt.incorrect { border-color: var(--red); background: rgba(248,113,113,0.1); }
.quiz-opt .letter {
  width: 26px; height: 26px; border-radius: 7px; display: flex; align-items: center;
  justify-content: center; font-weight: 700; font-size: 0.78rem; flex-shrink: 0;
  background: var(--card); border: 1px solid var(--border); color: var(--text-muted);
}
.quiz-opt.selected .letter { background: var(--accent); color: #070b14; border-color: var(--accent); }
.quiz-opt.correct .letter { background: var(--green); color: #070b14; border-color: var(--green); }
.quiz-opt.incorrect .letter { background: var(--red); color: #070b14; border-color: var(--red); }
.quiz-explanation {
  margin-top: 12px; padding: 14px 16px; border-radius: 10px; font-size: 0.88rem;
  border: 1px solid; display: none;
}
.quiz-explanation.show { display: block; }
.quiz-explanation.correct-exp { border-color: rgba(74,222,128,0.3); background: rgba(74,222,128,0.06); color: var(--text-secondary); }
.quiz-explanation.incorrect-exp { border-color: rgba(248,113,113,0.3); background: rgba(248,113,113,0.06); color: var(--text-secondary); }

/* SCORE BAR */
.score-bar {
  background: var(--surface); border: 1px solid var(--border); border-radius: 14px;
  padding: 18px 22px; display: flex; align-items: center; gap: 16px; margin-bottom: 20px;
}
.score-bar .score-num { font-size: 2rem; font-weight: 800; background: var(--gradient); -webkit-background-clip: text; background-clip: text; -webkit-text-fill-color: transparent; }
.score-bar .score-label { color: var(--text-muted); font-size: 0.85rem; }

/* BUTTONS */
.btn-submit {
  background: var(--gradient); color: #070b14; border: none; padding: 14px 28px;
  border-radius: 12px; font-weight: 700; font-size: 0.95rem; cursor: pointer;
  font-family: inherit; transition: transform .15s, box-shadow .15s;
  box-shadow: 0 8px 30px var(--accent-glow);
}
.btn-submit:hover { transform: translateY(-2px); box-shadow: 0 12px 40px var(--accent-glow); }

/* FOOTER */
.footer { margin-top: 60px; padding-top: 24px; border-top: 1px solid var(--border); text-align: center; color: var(--text-muted); font-size: 0.82rem; }

@media (max-width: 900px) {
  .sidebar { display: none; }
  .main { margin-left: 0 !important; margin-right: 0 !important; padding: 24px 20px 60px; }
  .progress-fill { left: 0 !important; right: 0 !important; }
}
</style>
</head>
<body>

<div class="progress-bar"><div class="progress-fill" id="progressFill"></div></div>

<nav class="sidebar" id="sidebar">
  <div class="sidebar-title">${(lesson.title || ui.untitled).replace(/</g, "&lt;")}</div>
  <div class="sidebar-label">${ui.sections}</div>
  <div id="navSections"></div>
  ${lesson.glossary?.length ? `<div class="sidebar-label" style="margin-top:12px">${ui.glossary}</div><a href="#glossary">${ui.glossary} (${lesson.glossary.length})</a>` : ""}
  ${lesson.quiz?.length ? `<div class="sidebar-label" style="margin-top:12px">${ui.quiz}</div><a href="#quiz">${ui.quiz} (${lesson.quiz.length} ${ui.questions})</a>` : ""}
</nav>

<div class="main">
  <div class="hero">
    <h1>${(lesson.title || ui.untitled).replace(/</g, "&lt;")}</h1>
    <div class="meta">
      <span class="badge">📚 ${lesson.sections?.length ?? 0} ${ui.sections}</span>
      <span class="badge">📖 ${lesson.glossary?.length ?? 0} ${ui.glossary}</span>
      <span class="badge">❓ ${lesson.quiz?.length ?? 0} ${ui.questions}</span>
    </div>
  </div>

  <div id="sectionsContainer"></div>

  ${lesson.glossary?.length ? `
  <div class="glossary-section" id="glossary">
    <h2 style="font-size:1.3rem;font-weight:800;margin-bottom:18px">${ui.glossary}</h2>
    <dl class="glossary-grid" id="glossaryGrid"></dl>
  </div>` : ""}

  ${lesson.quiz?.length ? `
  <div class="quiz-section" id="quiz">
    <h2 style="font-size:1.3rem;font-weight:800;margin-bottom:18px">${ui.quiz}</h2>
    <div class="score-bar" id="scoreBar" style="display:none">
      <div class="score-num" id="scoreNum">0%</div>
      <div><div class="score-label" id="scoreLabel">${ui.score}</div></div>
    </div>
    <div id="quizContainer"></div>
    <button class="btn-submit" id="submitBtn" style="margin-top:18px">${ui.submit}</button>
  </div>` : ""}

  <div class="footer">${ui.generatedBy} &middot; ${new Date().toLocaleDateString(lang === "ar" ? "ar-SA" : "en-US", { year: "numeric", month: "long", day: "numeric" })}</div>
</div>

<script>
(function() {
  var sections = ${sectionsJson};
  var glossary = ${glossaryJson};
  var quiz = ${quizJson};
  var lang = "${lang}";
  var ui = ${JSON.stringify(ui)};
  var answered = {};
  var selected = {};

  // Render sections
  var container = document.getElementById("sectionsContainer");
  var navContainer = document.getElementById("navSections");
  sections.forEach(function(s, i) {
    var id = "section-" + i;
    var card = document.createElement("div");
    card.className = "section-card open";
    card.id = id;
    card.innerHTML = '<div class="section-header" onclick="toggleSection(' + i + ')">' +
      '<h2>' + escHtml(s.heading) + '</h2>' +
      '<div class="toggle">' + (lang === "ar" ? "▲" : "▲") + '</div></div>' +
      '<div class="section-body"><p>' + escHtml(s.content) + '</p></div>';
    container.appendChild(card);

    var link = document.createElement("a");
    link.href = "#" + id;
    link.textContent = s.heading;
    link.className = "nav-link";
    navContainer.appendChild(link);
  });

  // Render glossary
  if (glossary.length) {
    var gGrid = document.getElementById("glossaryGrid");
    glossary.forEach(function(g) {
      var item = document.createElement("div");
      item.className = "glossary-item";
      item.innerHTML = "<dt>" + escHtml(g.term) + "</dt><dd>" + escHtml(g.definition) + "</dd>";
      gGrid.appendChild(item);
    });
  }

  // Render quiz
  if (quiz.length) {
    var qContainer = document.getElementById("quizContainer");
    var letters = ["A", "B", "C", "D"];
    quiz.forEach(function(q, qi) {
      var qDiv = document.createElement("div");
      qDiv.className = "quiz-question";
      qDiv.id = "quiz-q-" + qi;
      var optsHtml = q.options.map(function(o, oi) {
        return '<div class="quiz-opt" data-q="' + qi + '" data-o="' + oi + '" onclick="selectOpt(' + qi + ',' + oi + ')">' +
          '<div class="letter">' + letters[oi] + '</div><div>' + escHtml(o) + '</div></div>';
      }).join("");
      qDiv.innerHTML = '<div><span class="q-num">' + (qi + 1) + '</span><span class="q-text">' + escHtml(q.question) + '</span></div>' +
        '<div class="quiz-options">' + optsHtml + '</div>' +
        '<div class="quiz-explanation" id="exp-' + qi + '">' + escHtml(q.explanation) + '</div>';
      qContainer.appendChild(qDiv);
    });

    document.getElementById("submitBtn").addEventListener("click", submitQuiz);
  }

  // Toggle section
  window.toggleSection = function(i) {
    var card = document.getElementById("section-" + i);
    card.classList.toggle("open");
  };

  // Select quiz option
  window.selectOpt = function(qi, oi) {
    if (answered[qi]) return;
    selected[qi] = oi;
    var opts = document.querySelectorAll('[data-q="' + qi + '"]');
    opts.forEach(function(o) { o.classList.remove("selected"); });
    opts[oi].classList.add("selected");
  };

  // Submit quiz
  function submitQuiz() {
    var correct = 0;
    quiz.forEach(function(q, qi) {
      answered[qi] = true;
      var opts = document.querySelectorAll('[data-q="' + qi + '"]');
      opts.forEach(function(o) {
        var oIdx = parseInt(o.getAttribute("data-o"));
        o.style.cursor = "default";
        if (oIdx === q.correctIndex) o.classList.add("correct");
        else if (oIdx === selected[qi] && selected[qi] !== q.correctIndex) o.classList.add("incorrect");
        o.classList.remove("selected");
      });
      var exp = document.getElementById("exp-" + qi);
      exp.classList.add("show");
      if (selected[qi] === q.correctIndex) { correct++; exp.classList.add("correct-exp"); }
      else exp.classList.add("incorrect-exp");
    });
    var pct = Math.round((correct / quiz.length) * 100);
    var scoreBar = document.getElementById("scoreBar");
    scoreBar.style.display = "flex";
    document.getElementById("scoreNum").textContent = pct + "%";
    document.getElementById("scoreLabel").textContent = correct + " / " + quiz.length + " " + (lang === "ar" ? "صحيح" : "correct");
    document.getElementById("submitBtn").style.display = "none";
  }

  // Progress bar
  window.addEventListener("scroll", function() {
    var h = document.documentElement.scrollHeight - window.innerHeight;
    var pct = h > 0 ? (window.scrollY / h) * 100 : 0;
    document.getElementById("progressFill").style.width = pct + "%";
    // Active nav link
    var sections2 = document.querySelectorAll(".section-card");
    var links = document.querySelectorAll(".nav-link");
    var current = 0;
    sections2.forEach(function(s, i) {
      if (window.scrollY >= s.offsetTop - 120) current = i;
    });
    links.forEach(function(l, i) { l.classList.toggle("active", i === current); });
  });

  function escHtml(t) { var d = document.createElement("div"); d.textContent = t; return d.innerHTML; }
})();
</script>
</body>
</html>`;
}
